#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_instance="0.0.1"
  jq -n --arg fogg_instance "$ver_fogg_instance" '{fogg_instance: $fogg_instance}'
}

version "$@"
